name: relay
description: A secure messenger app. 
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  cryptography: ^2.5.0
  database_repository:
    path: packages/database_repository
  equatable: ^2.0.3
  firebase_core: ^2.1.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_ui_avatars: ^0.0.2
  font_awesome_flutter: ^10.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  google_fonts: ^4.0.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  local_auth: ^2.1.6
  local_storage_repository:
    path: packages/local_storage_repository
  messaging_repository:
    path: packages/messaging_repository
  meta: ^1.7.0
  mime: ^1.0.4
  qr_flutter: ^4.1.0
  storage_bucket_repository:
    path: packages/storage_bucket_repository
  uni_links: ^0.5.1
  video_player: ^2.7.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

# dependency_overrides:
#   bloc:
#     path: ../../packages/bloc
#   bloc_test:
#     path: ../../packages/bloc_test
#   flutter_bloc:
#     path: ../../packages/flutter_bloc
