name: cryptography_repository 
description: Dart package which manages the cryptography domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # local_storage_repository:
  #   path: ../local_storage_repository
  hive_generator: ^2.0.1
  webcrypto: ^0.5.3

dev_dependencies:

