name: messaging_repository
description: Dart package which manages the messaging domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  authentication_repository:
    path: ../authentication_repository
  database_repository:
    path: ../database_repository
  firebase_core: ^2.12.0
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  storage_bucket_repository:
    path: ../storage_bucket_repository
  mime: ^1.0.4

dev_dependencies:
  build_runner: ^2.4.6
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  plugin_platform_interface: ^2.1.4
